package conversation

import "strings"

// NormalizeUserPrompt 清理客户端以 user 角色注入的元数据，并保留真实输入的完整格式。
func NormalizeUserPrompt(prompt string) string {
	prompt = strings.TrimSpace(strings.ReplaceAll(prompt, "\r\n", "\n"))
	if prompt == "" {
		return ""
	}

	if queryText, ok := promptTagContent(prompt, "user_query"); ok {
		if queryText = strings.TrimSpace(queryText); queryText != "" {
			return queryText
		}
	}

	for _, tag := range []string{"user_info", "system_reminder", "system-reminder", "agent_notification", "agent-notification"} {
		prompt = stripPromptTagBlocks(prompt, tag)
	}
	prompt = strings.TrimSpace(prompt)
	if isAutoInjectedAgentPrompt(prompt) {
		return ""
	}
	return prompt
}

func promptTagContent(prompt string, tag string) (string, bool) {
	_, contentStart, contentEnd, _, ok := findPromptTagBlock(prompt, tag)
	if !ok {
		return "", false
	}
	return prompt[contentStart:contentEnd], true
}

func stripPromptTagBlocks(prompt string, tag string) string {
	for {
		start, _, _, end, ok := findPromptTagBlock(prompt, tag)
		if !ok {
			return prompt
		}
		prompt = prompt[:start] + prompt[end:]
	}
}

func findPromptTagBlock(prompt string, tag string) (start int, contentStart int, contentEnd int, end int, ok bool) {
	lower := strings.ToLower(prompt)
	openPrefix := "<" + strings.ToLower(tag)
	start = strings.Index(lower, openPrefix)
	if start < 0 {
		return 0, 0, 0, 0, false
	}
	afterName := start + len(openPrefix)
	if afterName >= len(lower) || (lower[afterName] != '>' && lower[afterName] != ' ' && lower[afterName] != '\t' && lower[afterName] != '\n') {
		return 0, 0, 0, 0, false
	}
	openEndRelative := strings.Index(lower[afterName:], ">")
	if openEndRelative < 0 {
		return 0, 0, 0, 0, false
	}
	contentStart = afterName + openEndRelative + 1
	closeTag := "</" + strings.ToLower(tag) + ">"
	closeRelative := strings.Index(lower[contentStart:], closeTag)
	if closeRelative < 0 {
		return 0, 0, 0, 0, false
	}
	contentEnd = contentStart + closeRelative
	end = contentEnd + len(closeTag)
	return start, contentStart, contentEnd, end, true
}

func isAutoInjectedAgentPrompt(prompt string) bool {
	trimmed := strings.TrimSpace(prompt)
	if trimmed == "" {
		return false
	}
	lower := strings.ToLower(trimmed)

	if strings.HasPrefix(lower, "# agents.md instructions") ||
		strings.Contains(lower, "agents.md instructions for") ||
		strings.HasPrefix(lower, "<environment_context>") ||
		strings.HasPrefix(lower, "<user_instructions>") ||
		strings.HasPrefix(lower, "<agent_transcripts>") ||
		strings.HasPrefix(lower, "<system_reminder>") ||
		strings.HasPrefix(lower, "<system-reminder>") ||
		strings.HasPrefix(lower, "<agent_notification>") ||
		strings.HasPrefix(lower, "<agent-notification>") ||
		strings.HasPrefix(lower, "another language model started to solve this problem") ||
		strings.HasPrefix(lower, "caveat: the messages below were generated by the user") ||
		strings.HasPrefix(lower, "this session is being continued from a previous conversation") ||
		strings.HasPrefix(lower, "<command-name>") ||
		strings.HasPrefix(lower, "<command-message>") ||
		strings.HasPrefix(lower, "<command-args>") ||
		strings.HasPrefix(lower, "<local-command-stdout>") ||
		strings.HasPrefix(lower, "<local-command-stderr>") {
		return true
	}

	return strings.HasPrefix(lower, "---") &&
		strings.Contains(lower, "\nname:") &&
		strings.Contains(lower, "\ndescription:") &&
		strings.Count(lower, "---") >= 2
}
