package sensitive

var builtinWordDefinitions = map[WordCategory][]wordDefinition{
	WordCategoryPornography: {
		{word: "招嫖", variants: []string{"招漂"}},
		{word: "裸聊", variants: []string{"果聊"}},
		{word: "卖淫", variants: []string{"卖银"}},
		{word: "嫖娼", variants: []string{"漂娼"}},
		{word: "色情交易", variants: []string{"色晴交易"}},
		{word: "淫秽视频", variants: []string{"淫会视频"}},
		{word: "成人视频交易", variants: []string{"成人视屏交易"}},
		{word: "上门性服务", variants: []string{"上门姓服务"}},
		{word: "无码成人视频", variants: []string{"无马成人视频"}},
		{word: "色情网站引流", variants: []string{"色晴网站引流"}},
		{word: "援交招募", variants: []string{"元交招募"}},
	},
	WordCategoryGambling: {
		{word: "赌博", variants: []string{"赌搏"}},
		{word: "博彩", variants: []string{"博采"}},
		{word: "赌场", variants: []string{"赌厂"}},
		{word: "赌球", variants: []string{"赌求"}},
		{word: "六合彩", variants: []string{"六和彩"}},
		{word: "网络赌博平台", variants: []string{"网络赌搏平台"}},
		{word: "博彩开户注册", variants: []string{"博采开户注册"}},
		{word: "赌场送彩金", variants: []string{"赌厂送彩金"}},
		{word: "赌盘代理", variants: []string{"堵盘代理"}},
		{word: "赌博群拉人", variants: []string{"赌搏群拉人"}},
		{word: "棋牌赌博充值", variants: []string{"棋牌赌搏充值"}},
		{word: "境外赌场开户", variants: []string{"境外赌厂开户"}},
	},
	WordCategoryDrugs: {
		{word: "冰毒", variants: []string{"冰读"}},
		{word: "海洛因", variants: []string{"海洛英"}},
		{word: "摇头丸", variants: []string{"摇头宛"}},
		{word: "K粉", variants: []string{"K纷"}},
		{word: "芬太尼", variants: []string{"芬太泥"}},
		{word: "制毒", variants: []string{"制读"}},
		{word: "贩毒", variants: []string{"贩读"}},
		{word: "毒品交易", variants: []string{"读品交易"}},
		{word: "吸毒工具出售", variants: []string{"吸读工具出售"}},
		{word: "大麻交易", variants: []string{"大嘛交易"}},
		{word: "毒品暗语交易", variants: []string{"读品暗语交易"}},
	},
	WordCategoryViolenceTerror: {
		{word: "炸弹制作", variants: []string{"炸弾制作"}},
		{word: "自制炸药", variants: []string{"自制炸要"}},
		{word: "恐怖袭击", variants: []string{"恐布袭击"}},
		{word: "枪支制造", variants: []string{"木仓支制造"}},
		{word: "暗杀教程", variants: []string{"暗沙教程"}},
		{word: "屠杀行动计划", variants: []string{"屠沙行动计划"}},
		{word: "人体炸弹制作", variants: []string{"人体炸弾制作"}},
		{word: "袭击学校方案", variants: []string{"袭机学校方案"}},
		{word: "极端组织招募", variants: []string{"极端组枳招募"}},
		{word: "爆炸物配方", variants: []string{"爆乍物配方"}},
	},
	WordCategoryPolitical: {
		{word: "煽动颠覆国家政权", variants: []string{"煽动颠复国家政权"}},
		{word: "煽动分裂国家", variants: []string{"煽动分列国家"}},
		{word: "暴力推翻政府", variants: []string{"暴利推翻政府"}},
		{word: "非法政治组织招募", variants: []string{"非法政冶组织招募"}},
		{word: "民族分裂宣传", variants: []string{"民族分列宣传"}},
		{word: "策划冲击国家机关", variants: []string{"策划冲机国家机关"}},
		{word: "泄露国家秘密渠道", variants: []string{"泄漏国家秘密渠道"}},
		{word: "境外敌对组织招募", variants: []string{"境外敌兑组织招募"}},
		{word: "制作反政府暴力宣传", variants: []string{"制作反政付暴力宣传"}},
		{word: "组织非法暴力集会", variants: []string{"组织非法暴利集会"}},
	},
	WordCategoryIllegalCrime: {
		{word: "电信诈骗", variants: []string{"电信诈騙"}},
		{word: "盗取银行卡", variants: []string{"盗取银型卡"}},
		{word: "制作假证件", variants: []string{"制作甲证件"}},
		{word: "洗钱通道", variants: []string{"洗前通道"}},
		{word: "黑客入侵", variants: []string{"黒客入侵"}},
		{word: "窃取账号密码", variants: []string{"切取账号密码"}},
		{word: "信用卡套现", variants: []string{"信用卡套线"}},
		{word: "伪造公章", variants: []string{"为造公章"}},
		{word: "买卖个人信息", variants: []string{"买卖个人信习"}},
		{word: "勒索软件制作", variants: []string{"勒锁软件制作"}},
		{word: "绕过支付系统", variants: []string{"绕过支副系统"}},
		{word: "开锁盗窃教程", variants: []string{"开锁盗切教程"}},
	},
}
